# Generated by Django 4.2.1 on 2024-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_first_name_user_last_name_comment_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
