# Generated by Django 4.2.1 on 2024-03-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_title", models.CharField(max_length=255)),
                ("ride_description", models.TextField()),
                ("max_passengers", models.PositiveIntegerField(default=4)),
                ("departure", models.DateTimeField()),
                ("arrival", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Поездка",
                "verbose_name_plural": "Поездки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("canceled", "Отменено"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to="rides.ride",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на поездку",
                "verbose_name_plural": "Заявки на поездку",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="ride",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                related_name="rides",
                through="rides.RideRequest",
                to="users.user",
            ),
        ),
    ]
