# Generated by Django 5.0.2 on 2024-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_user_first_name_user_last_name_comment_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_title", models.CharField(max_length=255)),
                ("ride_description", models.TextField()),
                ("departure", models.DateTimeField()),
                ("arrival", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ManyToManyField(
                        blank=True, related_name="rides", to="users.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поездка",
                "verbose_name_plural": "Поездки",
                "ordering": ("-created_at",),
            },
        ),
    ]
