# Generated by Django 4.2.1 on 2024-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="max_passengers",
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
