# Generated by Django 4.2.1 on 2024-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_ride_max_passengers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="max_passengers",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
