# Generated by Django 4.2.1 on 2024-03-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_moderateschedule"),
        ("rides", "0003_alter_ride_max_passengers"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("canceled", "Отменено"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to="rides.ride",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на поездку",
                "verbose_name_plural": "Заявки на поездку",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="ride",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                related_name="rides",
                through="rides.RideRequest",
                to="users.user",
            ),
        ),
    ]
